language: julia
sudo: false
julia:
    - 0.4
    - 0.5
    - nightly
os:
    - linux
    - osx

matrix:
  allow_failures:
  - julia: nightly

notifications:
    email: false

before_install:
    - julia -e 'Pkg.add("Conda"); Pkg.checkout("Conda"); Pkg.build("Conda");'
