language: julia
sudo: false
julia:
    - release
    - nightly
notifications:
    email: false
addons:
  apt:
    packages:
    - libgmp-dev
script:
    - git clone https://github.com/sympy/symengine
    - cd symengine
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/local -DBUILD_SHARED_LIBS=yes -DBUILD_TESTS=no -DBUILD_BENCHMARKS=no .
    - make -j4 install
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib/
    - cd ..
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("SymEngine")'
    - julia -e 'Pkg.test("SymEngine")'

